### ISSUE TITLE
Body AddVelocity?

### ISSUE THREAD

**Issue by Eon1** [jakecoffman/cp#10]
I was using another version of Chipmunk for go (vova616's version ) and it had a method on the Body called AddVelocity that was very useful. I added it to your Body and it works great maybe you should add it ? 

```
func (body *Body) AddVelocity(x, y float64) {
	body.v.X += float64(x)
	body.v.Y += float64(y)
}  
```

**Comment by jakecoffman** [comment]
I probably won't add anything that isn't in the C library, sorry!

**Comment by Eon1** [comment]
I can understand that . I was a little hesitant to ask cause I saw that it wasn't included in the C library. But thanks for the quick response .
