### ISSUE TITLE
Concurrent access to queries

### ISSUE THREAD

**Issue by 20zinnm** [jakecoffman/cp#14]
I noticed that chipmunk seems to have its own, non-atomic(?) locking system. Are any query functions (such as BBQuery) safe for concurrent access as long as it is not updating simultaneously?

**Comment by jakecoffman** [comment]
I implemented the same locking as chipmunk but I haven't actually tried it in practice, so let me know if it works 😄 

It looks like it should be fine because each thread would be filling out a separate "context" object and then only the thread that fully releases the logic applies the context change.

**Comment by 20zinnm** [comment]
My experience has been that it works fine but sets the race detector off like nobody's business. The Go sync package calls race.Stop or something to indicate that there programmatically won't be a race condition, perhaps we should look at adding that?

Also, is there a reason built-in mutexes wouldn't work (sync.RWMutex comes to mind)? I understand that this is a direct port from the C version but it strikes me as needlessly complex in a language that implements synchronization in the stdlib. Idk, thoughts?

**Comment by jakecoffman** [comment]
Oh I get what you mean now about the lock not being atomic. I do want to stay close to the C version for upgrades, but also want the race detector to be happy. I'll do some experimenting because I don't know the right answer yet.

**Comment by 20zinnm** [comment]
Perhaps just use atomic functions to increment the lock?

**Comment by jakecoffman** [comment]
Yeah that's a good starting point.

**Comment by 20zinnm** [comment]
So am I to understand that all methods of Space are concurrent-safe if there is a nested context system implemented, or do I need to attach a mutex to it to prevent bodies from being added or removed during a step?

**Comment by 20zinnm** [comment]
Several methods, such as AddConstraint, will panic if the space is locked, so I take it that either Space locking means something else or it is not concurrently accessible. However, other methods, such as AddBody, do not check that the space is unlocked but still modify an array which would trigger the race detector.
