### ISSUE TITLE
ShapeQueries not implemeted?

### ISSUE THREAD

**Issue by steampoweredtaco** [jakecoffman/cp#23]
Hi! Awesome library.  I have a couple specific use case that would work perfect for the shape query api that is in the C implementation but I can't seem to find it in this port?  https://chipmunk-physics.net/release/ChipmunkLatest-Docs/#Queries-ShapeQueries

However I could probably work around this by adding a shape to bodies in the scene that are in the scene that don't move and add a sensor shape.  This isn't ideal for many of my use cases, but I could probably make it work.

**Comment by jakecoffman** [comment]
Done! Released in 1.2.0. 

I did a quit test but nothing visual, let me know if it's not working.

**Comment by steampoweredtaco** [comment]
Thank you! I'll let you know if I have any issues.
