### ISSUE TITLE
If the vector is zero, Normalize() returns NaN.

### ISSUE THREAD

**Issue by setanarut** [jakecoffman/cp#33]
If the vector is zero, Normalize() returns NaN. For example, If the player velocity vector is zero, an error is received. To fix it replace `math.SmallestNonzeroFloat64` -> `1e-15`

https://github.com/jakecoffman/cp/blob/e672e20ac29a4ee0422c8944e69fe6f5551e5dc2/vector.go#L89

```Go
zeroVector := cp.Vector{0, 0}
// Normalize Vector
fmt.Println(zeroVector.Mult(1.0 / (zeroVector.Length() + math.SmallestNonzeroFloat64)))
fmt.Println(zeroVector.Mult(1.0 / (zeroVector.Length() + 1e-15)))
// NaN,NaN
// 0.000000,0.000000
```

**Comment by jakecoffman** [comment]
Thanks, nice catch!
