### ISSUE TITLE
Can't iterate over static bodies

### ISSUE THREAD

**Issue by Peterculazh** [jakecoffman/cp#35]
Hello, currently I'm trying to collect positions of each body by using `space.EachBody`, but it iterates only for dynamic bodies and skipping for static bodies.
I'm using examples to make researching easier: 
```

type BallData struct {
	ID int
}

func update(space *cp.Space, dt float64) {
	space.Step(dt)
	space.EachBody(func(body *cp.Body) {
		position := body.Position()
		fmt.Printf("X: %f, Y: %f\n", position.X, position.Y)
	})
}

func main() {
	space := cp.NewSpace()

	space.SetGravity(cp.Vector{X: 0, Y: -75})
	groundBody := cp.NewStaticBody() // Creating static body
	ground := space.AddShape(cp.NewSegment(groundBody, cp.Vector{X: -75, Y: 15}, cp.Vector{X: 75, Y: 15}, 0))
	ground.SetFriction(1)

	mass := 1

	h := float64(10)
	w := float64(10)

	ballBody := space.AddBody(cp.NewBody(float64(mass), cp.INFINITY))
	ballBody.SetPosition(cp.Vector{20, 35})
	ballBody.UserData = &BallData{ID: 1}

	ball := space.AddShape(cp.NewBox(ballBody, w, h, 0))
	ball.SetFriction(0.55)
	space.AddConstraint(cp.NewRotaryLimitJoint(ballBody, ballBody, 0, 0))

	examples.Main(space, 1.0/60.0, update, examples.DefaultDraw)
}
```

I've investigated source code and there seems static body isn't append to array of static bodies in space because of exiting from function too earlier because of not passing conditions in `body.go` at 180 row
```
if body.space == nil {
	return
}
```
Either I'm doing something wrong, either there bug
Thank you

**Comment by jakecoffman** [comment]
Please refer to: http://chipmunk-physics.net/release/ChipmunkLatest-Docs/#cpSpace-Iterators

I think this is by design!

> Sleeping bodies are included, but **_static and kinematic bodies are not as they aren’t added to the space_**.

I guess keep your own list of static and kinematic bodies for iteration.
