### ISSUE TITLE
API Document help

### ISSUE THREAD

**Issue by PeterXGX** [jakecoffman/cp#36]
Is there any API Doc for who never used Chipmunk2D with C++ before?

**Comment by jakecoffman** [comment]
The docs here are the best reference: https://chipmunk-physics.net/release/ChipmunkLatest-Docs/

If you see some C code, don't be intimidated! It's pretty straight forward to convert in your head. For instance:

```c
cpVect cpBodyLocalToWorld(const cpBody *body, const cpVect v)
```

In Go this would be 

```go
func (body *Body) LocalToWorld(v Vector) Vector {
```

But to answer your question, no there's no Go specific docs.
