### ISSUE TITLE
ReindexShape

### ISSUE THREAD

**Issue by emicklei** [jakecoffman/cp#38]
Hi,

I am looking for the Go counterpart of `void cpSpaceReindexShape(cpSpace *space, cpShape *shape)` as documented in [Spatial Indexing:](https://chipmunk-physics.net/release/ChipmunkLatest-Docs/#cpSpace-SpatialIndexing).

If that is missing now then could you give suggestions for an implementation so I can send a PR?

Thanks

**Comment by jakecoffman** [comment]
It does look like it's missing, PRs are very welcome!

It looks pretty straight forward to convert. I try to keep it close to the C code in case of updates, since this is just a port. 

https://github.com/slembcke/Chipmunk2D/blob/d0239ef4599b3688a5a336373f7d0a68426414ba/src/cpSpace.c#L662-L672

**Comment by jakecoffman** [comment]
Released https://github.com/jakecoffman/cp/releases/tag/v2.1.0

Thanks again for the PR!
