### ISSUE TITLE
Space.AddShape() unexpectedly adds shape to body.

### ISSUE THREAD

**Issue by setanarut** [jakecoffman/cp#40]
`Space.AddShape()` unexpectedly adds shape to body.

https://github.com/jakecoffman/cp/blob/77433c8e0668a5c5c56420062f47346636803a12/space.go#L271

```Go
func main() {
  space := cp.NewSpace()
  
  body := cp.NewBody(1, 1)
  shape := cp.NewBox(body, 5, 5, 0)
  
  space.AddShape(shape) // adds shape to body
  
  body.EachShape(func(s *cp.Shape) {
  fmt.Println(s)
  })
  // *cp.PolyShape
}

```

**Comment by jakecoffman** [comment]
It's in the C code:

https://github.com/slembcke/Chipmunk2D/blob/d0239ef4599b3688a5a336373f7d0a68426414ba/src/cpSpace.c#L430
