### ISSUE TITLE
goreportcard issues

### ISSUE THREAD

**Issue by 200sc** [jakecoffman/cp#7]
Going to https://goreportcard.com/report/github.com/jakecoffman/cp reveals a few minor issues that should be easy to fix, probably the most significant being that [line 115 of space.go](https://github.com/jakecoffman/cp/blob/4c9738d5a28e8a3df3c6bdf905afa33f5b3c92b0/space.go#L115) should be on a pointer receiver instead of a struct itself.

**Comment by jakecoffman** [comment]
Thanks for this. I fixed the pointer receiver issue. I probably will not address cyclomatic complexities since this is a port and I want to keep the functions close to the original in case the Chipmunk authors start updating things.

**Comment by 200sc** [comment]
Yeah, cyclomatic complexity issues aren't a huge deal as long as its something that is being kept track of.
